---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: default.yml
  when: newrelic_loaded_os_family|default(False) == False

- name: New Relic Agent silent install
  command: newrelic-install install
  environment:
    NR_INSTALL_SILENT: true

- name: Configure New Relic Agent
  template:
    src: newrelic.ini.j2
    dest: /etc/php/7.4/mods-available/newrelic.ini
    group: root 
    owner: root
    mode: 0644
    #force: no
  notify:
    - Restart New Relic Daemon
    - Restart php-fpm 
    - Restart nginx
  when: newrelic_loaded_os_family|default(False) != False

- name: Delete unused newrelic.ini
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/php/7.4/fpm/conf.d/newrelic.ini
    - /etc/php/7.4/cli/conf.d/newrelic.ini
  changed_when: False
        
- name: Ensure New Relic Agent is started and enabled
  service:
    name: newrelic-daemon
    state: started
    enabled: yes
