---
- name: Restart New Relic Daemon
  service:
    name: newrelic-daemon
    state: restarted
- name: Restart php-fpm
  service:
    name: php7.4-fpm.service 
    state: restarted
- name: Restart nginx 
  service:
    name: nginx 
    state: restarted
